;**************************************************************************
;*                                                                        *
;*                                 OCaml                                  *
;*                                                                        *
;*                        Max Slater, Jane Street                         *
;*                                                                        *
;*   Copyright 2025 Jane Street Group LLC                                 *
;*                                                                        *
;*   All rights reserved.  This file is distributed under the terms of    *
;*   the GNU Lesser General Public License version 2.1, with the          *
;*   special exception on linking described in the file LICENSE.          *
;*                                                                        *
;**************************************************************************

(executable
 (name simdgen)
 (modes native)
 (modules simdgen defs))

(rule
 (targets instrs.ml externals.ml)
 (deps simdgen.exe arm64/advsimd.csv)
 (mode promote)
 (action
   (run ./simdgen.exe arm64/advsimd.csv)))
