(* Generated by backend/arm64_simdgen/simdgen.ml *)

open Arm64_simd_defs

type id =
  (* scalar intrinsics  *)
  | Round_f32x4
  | Zip1_f32
  | Zip1q_f32
  | Zip1q_f64
  | Zip2q_f64
  | Addq_i64
  | Subq_i64
  | Addq_f32
  | Subq_f32
  | Mulq_f32
  | Divq_f32
  | Minq_f32
  | Maxq_f32
  | Recpeq_f32
  | Sqrtq_f32
  | Rsqrteq_f32
  | Cvtq_s32_of_f32
  | Cvtq_f32_of_s32
  | Cvt_f64_f32
  | Paddq_f32
  | Cmp_f32
  | Cmpz_s32

(* type nonrec instr = id instr *)
