(* Generated by backend/arm64_simdgen/simdgen.ml *)

open Arm64_simd_defs

type id =
  | Round_f32
  | Round_f64
  | Round_f32x4
  | Round_f32_i64
  | Fmin_f32
  | Fmax_f32
  | Zip1_f32
  | Zip1q_f32
  | Zip1q_f64
  | Zip2q_f64
  | Addq_i64
  | Subq_i64
  | Addq_f32
  | Subq_f32
  | Mulq_f32
  | Divq_f32
  | Minq_f32
  | Maxq_f32
  | Recpeq_f32
  | Sqrtq_f32
  | Rsqrteq_f32
  | Cvtq_s32_of_f32
  | Cvtq_f32_of_s32
  | Cvt_f64_f32
  | Paddq_f32
  | Cmp_f32
  | Cmpz_s32

type nonrec instr = id instr

let pmovmskb_r64_X =
  { id = Pmovmskb_r64_X;
    args = [| { loc = Temp [| XMM |]; enc = RM_rm } |];
    res = Res { loc = Temp [| R64 |]; enc = RM_r };
    imm = false;
    mnemonic = "pmovmskb";
    enc =
      { prefix = Legacy { prefix = Prx_66; rex = Rex_none; escape = Esc_0F };
        rm_reg = Reg;
        opcode = 215
      }
  }
